language: node_js
node_js: node
cache: npm
script:
  - yarn test --env=jsdom --coverage --watchAll=false --testResultsProcessor jest-sonar-reporter
  - ls -al ./**/*.test.js
  - yarn sonar
# after_success:
#   - npm run coverage
