language: node_js
node_js: node
cache: npm
#Fix sonar blame issue
git:
  depth: false
script:
  - yarn test --env=jsdom --coverage --watchAll=false --testResultsProcessor jest-sonar-reporter
  - yarn sonar
